name: Build For Linux

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Install Dependencies
        run: sudo apt-get install -y libfuse-dev zlib1g-dev

      - name: Configure
        run: cmake -S standalone -B build/standalone

      - name: Build
        run: cmake --build build -j4

      - name: Make Release Body
        run: echo Built from \#`git rev-parse --short HEAD` > release.md

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/standalone/GhostFS"
          bodyFile: "release.md"
          prerelease: true
